# Generated by Django 5.1.2 on 2024-10-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_alter_borrowing_actual_date_returned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowing',
            old_name='actual_date_returned',
            new_name='actual_return_date',
        ),
        migrations.RenameField(
            model_name='borrowing',
            old_name='expected_date_returned',
            new_name='expected_return_date',
        ),
    ]
