# Generated by Django 5.1.2 on 2024-10-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0003_rename_actual_date_returned_borrowing_actual_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='expected_return_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
