# Generated by Django 5.1.2 on 2024-10-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0004_alter_borrowing_expected_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='expected_return_date',
            field=models.DateField(),
        ),
    ]
